# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - dya

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  JAVA_VERSION: '21'
  AZURE_WEBAPP_NAME: 'dya'  # ← Nombre exacto de tu App Service

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install

      - name: Rename and move JAR
        run: |
          mkdir deploy
          cp target/*.jar deploy/app.jar

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: deploy/app.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_379D0E5DAE144B56AF8724727DBF3EE6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C1718C7F5DC24BDA9ABA1EA1E29F098A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F4390F4176C64ECE9A2F95A23EDCAFAC }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: deploy/app.jar

          